# Generated by Django 4.1.1 on 2022-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, max_length=11, unique=True),
        ),
    ]
