# Generated by Django 4.1.1 on 2022-09-14 19:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='', max_length=11, null=True, unique=True),
        ),
    ]
