# Generated by Django 4.1.1 on 2022-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('destination', models.CharField(max_length=150)),
                ('destination_iata', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=150)),
                ('origin_iata', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
            ],
        ),
    ]
