# Generated by Django 4.1.1 on 2022-09-12 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(related_name='attend_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
