# Generated by Django 4.1.1 on 2022-09-13 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_event', '0002_events_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attend_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
